### ISSUE TITLE
[FEATURE] - Implement Add to Cart Functionality

### ISSUE THREAD

**Issue by VivekChatterjee** [VivekChatterjee/ecommerce#4]
Add to Cart feature has to be implemented for the website

**Comment by mayankch283** [comment]
Hello. Can I have a shot at this? I have a few ideas which will work. Kindly /assign

**Comment by VivekChatterjee** [comment]
Go ahead @mayankch283

**Comment by mayankch283** [comment]
Hello again. While working on the issue I had a question. Since there is no main cart page yet, can you please elaborate a little on how add to cart functionality is to be implemented? Or do you want me to add a main cart page as well?

**Comment by VivekChatterjee** [comment]
#10
