### ISSUE TITLE
[DOCUMENTATION] - Improve documentation of the repository

### ISSUE THREAD

**Issue by VivekChatterjee** [VivekChatterjee/ecommerce#5]
How can you improve?
You can raise multiple issues and PRs if you want:

- Beautify Readme, add Contributors images section, improve the content inside
- Beautify Contributing.md, improve the content inside

**Comment by ericmchen15** [comment]
Hi @VivekChatterjee , would one way to improve the Contributing.md be adding extra info/descriptions about each step. Like more info explaining how and/or what to do. I can also add a couple images if that helps (images of the steps being done).

**Comment by VivekChatterjee** [comment]
Go ahead @ericmchen15 . If possible, you can add contributors list to readme, for this you can raise different PR, whichever is cool with you.
